<a href="https://colab.research.google.com/github/KHUSHNADPARA-max/CPP/blob/main/Practical_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import io

In [2]:
import pandas

In [3]:
from google.colab import files
uploaded=files.upload()

Saving NBA_2018-19_Season - NBA_2018-19_Season.csv to NBA_2018-19_Season - NBA_2018-19_Season.csv

In [4]:
df = pandas.read_csv(io.BytesIO(uploaded['NBA_2018-19_Season - NBA_2018-19_Season.csv']))

In [5]:
df.head(5)

,Conference,Division,Team,Player,Age,Games,Games Started,Minutes Played,Field Goals,Field Goal Attempts,...,Free Throw Percentage,Offensive Rebounds,Defensive Rebounds,Total Rebounds,Assists,Steals,Blocks,Turnovers,Personal Fouls,Points
0,Eastern,Atlantic,Boston Celtics,Jayson Tatum,20,79,79,2455,466,1036,...,0.855,70,407,477,168,84,57,122,168,1243
1,Eastern,Atlantic,Boston Celtics,Kyrie Irving,26,67,67,2214,604,1241,...,0.873,71,264,335,464,103,34,172,167,1596
2,Eastern,Atlantic,Boston Celtics,Marcus Smart,24,80,60,2200,239,567,...,0.806,57,177,234,321,143,28,123,201,708
3,Eastern,Atlantic,Boston Celtics,Marcus Morris,29,75,53,2091,377,844,...,0.844,76,382,458,109,43,25,92,181,1046
4,Eastern,Atlantic,Boston Celtics,Al Horford,32,68,68,1973,387,723,...,0.821,120,338,458,283,59,86,102,126,925

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 622 entries, 0 to 621
Data columns (total 30 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Conference                       622 non-null    object
 1   Division                         622 non-null    object
 2   Team                             622 non-null    object
 3   Player                           622 non-null    object
 4   Age                              622 non-null    int64
 5   Games                            622 non-null    int64
 6   Games Started                    622 non-null    int64
 7   Minutes Played                   622 non-null    int64
 8   Field Goals                      622 non-null    int64
 9   Field Goal Attempts              622 non-null    int64
 10  Field Goal Percentage            616 non-null    float64
 11  3-Point Field Goals              622 non-null    int64
 12  3-Point Field Goal Attempts      622 non-null    int64
 13  3-Point Field Goal Percentage    578 non-null    float64
 14  2-Point Field Goals              622 non-null    int64
 15  2-Point Field Goal Attempts      622 non-null    int64
 16  2-Point Field Goal Percentage    607 non-null    float64
 17  Effective Field Goal Percentage  616 non-null    float64
 18  Free Throws                      622 non-null    int64
 19  Free Throw Attempts              622 non-null    int64
 20  Free Throw Percentage            581 non-null    float64
 21  Offensive Rebounds               622 non-null    int64
 22  Defensive Rebounds               622 non-null    int64
 23  Total Rebounds                   622 non-null    int64
 24  Assists                          622 non-null    int64
 25  Steals                           622 non-null    int64
 26  Blocks                           622 non-null    int64
 27  Turnovers                        622 non-null    int64
 28  Personal Fouls                   622 non-null    int64
 29  Points                           622 non-null    int64
dtypes: float64(5), int64(21), object(4)
memory usage: 145.9+ KB

In [7]:
df['Age'].min()

19

In [8]:
df.groupby('Age').mean()

<ipython-input-8-16c96bc1028d>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df.groupby('Age').mean()

,Games,Games Started,Minutes Played,Field Goals,Field Goal Attempts,Field Goal Percentage,3-Point Field Goals,3-Point Field Goal Attempts,3-Point Field Goal Percentage,2-Point Field Goals,...,Free Throw Percentage,Offensive Rebounds,Defensive Rebounds,Total Rebounds,Assists,Steals,Blocks,Turnovers,Personal Fouls,Points
Age,,,,,,,,,,,,,,,,,,,,,
19,39.727273,22.363636,898.000000,167.272727,379.181818,0.418000,38.090909,116.454545,0.242636,129.181818,...,0.625091,47.909091,149.545455,197.454545,76.181818,24.727273,23.636364,62.454545,81.363636,462.727273
20,55.000000,32.520000,1256.720000,203.760000,444.960000,0.440840,45.560000,135.320000,0.313652,158.200000,...,0.724130,55.640000,161.800000,217.440000,113.120000,39.920000,31.840000,72.680000,118.040000,533.680000
21,36.060000,15.400000,724.100000,119.620000,259.020000,0.419583,28.160000,83.680000,0.278171,91.460000,...,0.668911,36.800000,107.740000,144.540000,65.780000,21.580000,18.540000,42.940000,68.880000,317.440000
22,38.280000,15.800000,827.900000,146.480000,316.540000,0.421480,35.580000,101.380000,0.311021,110.900000,...,0.657891,32.020000,114.200000,146.220000,95.020000,27.060000,14.880000,51.140000,72.780000,384.040000
23,33.417910,13.417910,715.761194,124.343284,271.895522,0.434545,32.134328,94.223881,0.311177,92.208955,...,0.725895,32.940299,110.567164,143.507463,63.805970,20.313433,14.865672,41.298507,61.686567,333.656716
24,45.226415,21.094340,1007.264151,167.679245,355.150943,0.440528,36.339623,107.226415,0.283612,131.339623,...,0.739077,48.490566,158.452830,206.943396,103.509434,33.849057,24.113208,58.075472,91.830189,450.641509
25,45.673077,17.750000,1013.673077,176.057692,368.211538,0.441078,42.461538,118.923077,0.318367,133.596154,...,0.760500,52.250000,142.615385,194.865385,82.923077,34.980769,23.461538,49.538462,92.519231,467.961538
26,41.909091,19.000000,998.327273,178.236364,380.236364,0.471018,49.090909,133.545455,0.321340,129.145455,...,0.771160,45.000000,142.109091,187.109091,95.763636,30.090909,17.363636,49.690909,82.618182,478.472727
27,41.727273,18.431818,968.159091,155.886364,345.454545,0.435349,56.727273,154.431818,0.359762,99.159091,...,0.773575,35.000000,122.500000,157.500000,84.636364,27.636364,14.931818,44.022727,75.272727,429.840909
28,41.020000,23.240000,1034.420000,181.220000,406.400000,0.438640,59.920000,167.580000,0.348894,121.300000,...,0.746234,35.940000,144.240000,180.180000,128.480000,36.100000,18.800000,62.860000,86.360000,499.280000
29,45.205882,25.823529,1113.676471,214.441176,460.294118,0.431765,53.764706,152.000000,0.279906,160.676471,...,0.758094,53.705882,182.000000,235.705882,111.176471,39.088235,23.676471,71.117647,98.529412,589.794118
30,47.805556,25.888889,1168.361111,204.083333,438.694444,0.463629,61.305556,166.333333,0.324688,142.777778,...,0.756714,43.277778,179.916667,223.194444,143.555556,33.138889,24.166667,71.694444,94.722222,561.027778
31,47.409091,27.727273,1032.590909,152.681818,330.863636,0.447682,58.136364,150.772727,0.357524,94.545455,...,0.770864,36.727273,126.681818,163.409091,120.681818,33.818182,19.727273,52.772727,88.772727,420.954545
32,39.884615,20.461538,1000.884615,152.461538,346.961538,0.416269,52.653846,148.115385,0.337385,99.807692,...,0.788885,32.692308,130.653846,163.346154,115.038462,30.500000,16.846154,53.769231,80.538462,429.692308
33,43.000000,24.157895,1054.315789,155.157895,337.315789,0.423526,43.789474,124.736842,0.279000,111.368421,...,0.752588,53.473684,152.947368,206.421053,89.157895,37.263158,22.052632,48.052632,89.842105,424.631579
34,42.454545,22.272727,959.000000,176.181818,381.545455,0.458000,51.181818,140.000000,0.323444,125.000000,...,0.776455,33.545455,163.272727,196.818182,133.727273,27.909091,18.545455,62.454545,77.909091,488.000000
35,57.333333,7.000000,996.666667,108.666667,255.333333,0.416000,47.333333,141.000000,0.349333,61.333333,...,0.709667,21.333333,117.333333,138.666667,119.333333,34.000000,24.000000,40.333333,90.666667,315.333333
36,38.250000,2.000000,606.000000,83.500000,169.500000,0.563250,3.250000,13.750000,0.085000,80.250000,...,0.636000,35.000000,93.250000,128.250000,67.500000,15.000000,11.250000,32.000000,62.500000,213.500000
37,47.750000,0.500000,962.750000,165.500000,390.750000,0.419250,59.500000,166.500000,0.355750,106.000000,...,0.791000,22.250000,104.500000,126.750000,124.250000,25.000000,13.250000,65.000000,72.000000,449.000000
38,26.000000,1.750000,411.250000,56.750000,141.250000,0.340750,18.250000,56.750000,0.291250,38.500000,...,0.701500,8.250000,54.000000,62.250000,70.750000,9.500000,6.750000,29.500000,28.250000,162.750000
40,51.000000,20.000000,795.000000,135.000000,376.000000,0.359000,64.000000,205.000000,0.312000,71.000000,...,0.780000,5.000000,153.000000,158.000000,35.000000,9.000000,18.000000,18.000000,76.000000,373.000000
42,76.000000,9.000000,1330.000000,196.000000,468.000000,0.419000,123.000000,316.000000,0.389000,73.000000,...,0.712000,31.000000,163.000000,194.000000,87.000000,44.000000,27.000000,48.000000,141.000000,562.000000

Question 1. Find out the average age of the player who have played for NBA?

In [9]:
df['Age'].mean()

26.04823151125402

Question 2. Find out that each player have played how many games?

In [10]:
df[['Player', 'Games']]

                   Player  Games
0            Jayson Tatum     79
1            Kyrie Irving     67
2            Marcus Smart     80
3           Marcus Morris     75
4              Al Horford     68
..                    ...    ...
617           Salah Mejri     36
618          Courtney Lee     22
619           Daryl Macon      8
620  Kostas Antetokounmpo      2
621          Ray Spalding      1

[622 rows x 2 columns]

Question 3. Total how many teams are there in NBA?

https://colab.research.google.com/drive/1xcgjqaebmnFI-7x0As29tWWPaNCy--NI#scrollTo=YzxoA9i9NoX9&printMode=true

In [11]:
df['Team'].nunique()

30

Question 4. What is the minimum age of the player that have played for NBA?

In [12]:
df['Age'].min()

19

Question 5. What is the Maximum age of the player that have played for NBA and display its details?

In [13]:
df['Age'].max()

42

In [14]:
df.loc[df['Age']==42]

,Conference,Division,Team,Player,Age,Games,Games Started,Minutes Played,Field Goals,Field Goal Attempts,...,Free Throw Percentage,Offensive Rebounds,Defensive Rebounds,Total Rebounds,Assists,Steals,Blocks,Turnovers,Personal Fouls,Points
302,Eastern,Southeast,Atlanta Hawks,Vince Carter,42,76,9,1330,196,468,...,0.712,31,163,194,87,44,27,48,141,562

Question 6. Find out how many games have been organized in Eastern region.

In [16]:
east = df[df.Conference == 'Eastern'].Games.sum()
east

12976

Question 7. Find out the how many regions are there, where the games have been organized?

In [17]:
r = df[['Conference']].nunique().Conference
r

2

Question 8. Display the list of the player who have played in the team called "Boston Celtics".

In [18]:
df[df.Team == 'Boston Celtics']

,Conference,Division,Team,Player,Age,Games,Games Started,Minutes Played,Field Goals,Field Goal Attempts,...,Free Throw Percentage,Offensive Rebounds,Defensive Rebounds,Total Rebounds,Assists,Steals,Blocks,Turnovers,Personal Fouls,Points
0,Eastern,Atlantic,Boston Celtics,Jayson Tatum,20,79,79,2455,466,1036,...,0.855,70,407,477,168,84,57,122,168,1243
1,Eastern,Atlantic,Boston Celtics,Kyrie Irving,26,67,67,2214,604,1241,...,0.873,71,264,335,464,103,34,172,167,1596
2,Eastern,Atlantic,Boston Celtics,Marcus Smart,24,80,60,2200,239,567,...,0.806,57,177,234,321,143,28,123,201,708
3,Eastern,Atlantic,Boston Celtics,Marcus Morris,29,75,53,2091,377,844,...,0.844,76,382,458,109,43,25,92,181,1046
4,Eastern,Atlantic,Boston Celtics,Al Horford,32,68,68,1973,387,723,...,0.821,120,338,458,283,59,86,102,126,925
5,Eastern,Atlantic,Boston Celtics,Jaylen Brown,22,74,25,1913,368,792,...,0.658,65,248,313,100,69,32,99,186,964
6,Eastern,Atlantic,Boston Celtics,Gordon Hayward,28,72,18,1863,296,635,...,0.834,51,271,322,244,62,23,105,104,825
7,Eastern,Atlantic,Boston Celtics,Terry Rozier,24,79,14,1791,258,666,...,0.785,32,275,307,231,68,21,68,101,708
8,Eastern,Atlantic,Boston Celtics,Daniel Theis,26,66,2,908,146,266,...,0.737,87,138,225,68,21,42,33,161,374
9,Eastern,Atlantic,Boston Celtics,Aron Baynes,32,51,18,821,105,223,...,0.855,88,152,240,57,12,34,40,125,284
10,Eastern,Atlantic,Boston Celtics,Semi Ojeleye,24,56,3,594,67,158,...,0.615,24,62,86,23,10,4,19,43,186
11,Eastern,Atlantic,Boston Celtics,Brad Wanamaker,29,36,0,343,50,105,...,0.857,3,38,41,56,12,2,19,34,140
12,Eastern,Atlantic,Boston Celtics,Robert Williams,21,32,2,283,36,51,...,0.600,27,54,81,7,9,40,10,36,81
13,Eastern,Atlantic,Boston Celtics,Guerschon Yabusele,23,41,1,251,35,77,...,0.682,23,30,53,15,8,7,15,32,94
14,Eastern,Atlantic,Boston Celtics,PJ Dozier,22,6,0,51,8,21,...,0.500,6,11,17,5,2,0,0,2,19
15,Eastern,Atlantic,Boston Celtics,R.J. Hunter,25,1,0,26,6,13,...,0.500,1,2,3,3,1,0,0,3,17
16,Eastern,Atlantic,Boston Celtics,Greg Monroe,28,2,0,5,3,5,...,NaN,3,0,3,1,0,0,0,0,6

Question 9. Find out the total number of games organized in each division?

In [20]:
df.groupby('Division')['Games'].sum()

Division
Atlantic     4319
Central      4345
Northwest    4396
Pacific      4453
Southeast    4312
Southwest    4276
Name: Games, dtype: int64

Question 10. Which player have scored the maximum number of goals?

In [21]:
max_goal = df[['Field Goals']].max()
df[df['Field Goals']== max_goal['Field Goals']]

,Conference,Division,Team,Player,Age,Games,Games Started,Minutes Played,Field Goals,Field Goal Attempts,...,Free Throw Percentage,Offensive Rebounds,Defensive Rebounds,Total Rebounds,Assists,Steals,Blocks,Turnovers,Personal Fouls,Points
514,Western,Southwest,Houston Rockets,James Harden,29,78,78,2867,843,1909,...,0.879,66,452,518,586,158,58,387,244,2818

Question 11. Which player have the lowest number of personal fouls?

In [22]:
min_fault = df[['Personal Fouls']].min()
df[df['Personal Fouls'] == min_fault['Personal Fouls']][['Player','Personal Fouls']]

                    Player  Personal Fouls
16             Greg Monroe               0
130           Trevon Duval               0
147           Ike Anigbogu               0
165  Sviatoslav Mykhailiuk               0
167            Zach Lofton               0
189             Tyler Ulis               0
215           Kobi Simmons               0
216           John Holland               0
233           Troy Caupain               0
249            J.P. Macura               0
267            Yante Maten               0
268          Emanuel Terry               0
292           John Jenkins               0
293            Okaro White               0
315          Jordan Sibert               0
385         Donte Grantham               0
386            Tyler Davis               0
387            Jawun Evans               0
408            Mitch Creek               0
489           Andre Ingram               0
512            George King               0
534          Vince Edwards               0
536                Zhou Qi               0
579          D.J. Stephens               0
620   Kostas Antetokounmpo               0
621           Ray Spalding               0

Question 12. Which player have attempted the 3-points field goals the highest time and what are the percentage of it?

In [ ]:
maxAtt = df[['3-Point Field Goal Attempts']].max()
df[df['3-Point Field Goal Attempts'] == maxAtt['3-Point Field Goal Attempts']][['Player', '3-Point Field Goal Attempts', '3-Point Field

Question 13. What is the average point scored by all the players?

In [26]:
df['Average Points'] = df["Games"]/df["Points"]
df[['Player','Average Points']]

                   Player  Average Points
0            Jayson Tatum        0.063556
1            Kyrie Irving        0.041980
2            Marcus Smart        0.112994
3           Marcus Morris        0.071702
4              Al Horford        0.073514
..                    ...             ...
617           Salah Mejri        0.255319
618          Courtney Lee        0.275000
619           Daryl Macon        0.275862
620  Kostas Antetokounmpo        1.000000
621          Ray Spalding             inf

[622 rows x 2 columns]

Question 14. Find out the average age of players division wise?

In [27]:
df.groupby("Division")["Age"].mean()

Division
Atlantic     25.728972
Central      25.736364
Northwest    25.709677
Pacific      26.104762
Southeast    25.979798
Southwest    26.981481
Name: Age, dtype: float64

Question 15. Find out the total number of fouls in each team?

In [28]:
df.groupby("Team")["Personal Fouls"].sum()

Team
Atlanta Hawks             1932
Boston Celtics            1670
Brooklyn Nets             1763
Charlotte Hornets         1550
Chicago Bulls             1663
Cleveland Cavaliers       1642
Dallas Mavericks          1650
Denver Nuggets            1644
Detroit Pistons           1811
Golden State Warriors     1757
Houston Rockets           1803
Indiana Pacers            1594
Los Angeles Clippers      1913
Los Angeles Lakers        1701
Memphis Grizzlies         1801
Miami Heat                1712
Milwaukee Bucks           1608
Minnesota Timberwolves    1664
New Orleans Pelicans      1732
New York Knicks           1713
Oklahoma City Thunder     1839
Orlando Magic             1526
Philadelphia 76ers        1745
Phoenix Suns              1932
Portland Trail Blazers    1669
Sacramento Kings          1751
San Antonio Spurs         1487
Toronto Raptors           1724
Utah Jazz                 1728
Washington Wizards        1701
Name: Personal Fouls, dtype: int64